""" 
Serializers for the Movie Theater Booking REST API.

Converts Django model instances into JSON representations 
and handles validation for incoming API requests.
"""

from rest_framework import serializers
from .models import Movie, Seat, Booking

class MovieSerializer(serializers.ModelSerializer):
    """
    Serializer for the Movie model.

    Converts Movie instances to and from JSON format.
    """
    class Meta:
        model = Movie
        fields = ['id', 'title', 'description', 'release_date', 'duration']

class SeatSerializer(serializers.ModelSerializer):
    """
    Serializer for the Seat model.

    Converts Seat instances to and from JSON format.
    """

    class Meta: 
        model = Seat
        fields = ['id', 'seat_number', 'is_booked']

class BookingSerializer(serializers.ModelSerializer):
    """
    Serializer for the Booking model.

    Includes validation to prevent blocking seats that are already reserved.
    """

    class Meta: 
        model = Booking
        fields = ['id', 'movie', 'seat', 'user', 'booking_date']

        # This field is auto-generated by Django ORM upon creation
        read_only_fields = ['booking_date']

    def validate(self, data):
        """
        Validate that the requested seat is available for booking.
        """

        seat = data.get('seat')

        # Check if seat is already reserved before confirming booking
        if seat and seat.is_booked:
            raise serializers.ValidationError("This seat is already booked.")

        return data